namespace Roblox.Models.Staff;

public enum Access
{
    GetStats,
    GetAlert,
    SetAlert,
    CreateUser,
    // 4 retired: ForceApplication (application process removed). Ordinal preserved (int-backed).
    GetPendingGroupIcons = 5,
    GetAssetModerationDetails,
    GetPendingModerationItems,
    GetPendingModerationGameIcons,
    SetGameIconModerationStatus,
    SetAssetModerationStatus,
    SetGroupIconModerationStatus,
    GetGroupManageInfo,
    GetUserJoinCount,
    GetUsersList,
    GetUserDetailed,
    UnbanUser,
    BanUser,
    GetUserModerationHistory,
    CreateMessage,
    GetAdminMessages,
    NullifyPassword,
    DestroyAllSessionsForUser,
    LockAccount,
    RegenerateAvatar,
    ResetAvatar,
    GetAdminLogs,
    GetUserBadges,
    GiveUserBadge,
    DeleteUserBadge,
    GiveUserRobux,
    GetUserCollectibles,
    RemoveUserItem,
    TrackItem,
    GiveUserItem,
    DeleteUser,
    GetPreviousUsernames,
    DeleteUsername,
    DeleteComment,
    // 39 retired: DeleteForumPost (forums removed). Ordinal preserved — Access is
    // stored as an integer in user_permission, so downstream values must not shift.
    RequestAssetReRender = 40,
    GetProductDetails,
    SetAssetProduct,
    CreateAsset,
    CreateClothingAsset,
    // 45 retired: CopyClothingFromRoblox (clothing-stealer removed). Ordinal preserved (int-backed).
    CreateAssetVersion = 46,
    MigrateAssetFromRoblox,
    CreateGameForUser,
    RequestWebsiteUpdate,
    RunLottery,
    GetUserStatusHistory,
    DeleteUserStatus,
    GetUserCommentHistory,
    ManageFeatureFlags,
    GetUsersOnline,
    GetUsersInGame,
    GetUserTransactions,
    ResetUsername,
    ResetDescription,
    // 60/61/62 retired: ManageApplications, ClearApplications, ManageInvites
    // (application + invite systems removed). Ordinals preserved (int-backed).
    GetGroupWall = 63,
    DeleteGroupWallPost,
    GetAllAssetComments,
    GetAllUserStatuses,
    LockAndUnlockGroup,
    GetGroupStatus,
    DeleteGroupStatus,
    ResetGroup,
    // 71 retired: LockForumThread (forums removed). Ordinal preserved (int-backed).
    ManageReports = 72,
    GetAllAssetOwners,
    GetDetailsFromThumbnail,
    SetPermissions, // fake perm
    GetGameServers,
    MakeItemLimited,
    // 78 retired: CreateAssetCopiedFromRoblox (clothing-stealer copy endpoint removed). Ordinal preserved.
    CreateBundleCopiedFromRoblox = 79,
    GetSaleHistoryForAsset,
    RefundAndDeleteFirstPartyAssetSale,
    ManagePromocodes,
}